 [
  {
    id: "amar fullmoon_Very bad experience it the worst drink I had in my",
    reviewName: "amar fullmoon",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "Very bad experience it the worst drink I had in my life I wasted my money and my energy",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/grQikmATJkDys8ke8",
  }, {
    id: "Raid Ben_Very expressive, average food.\nMeal type\nBreakfast",
    reviewName: "Raid Ben",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "Very expressive, average food.\nMeal type\nBreakfast\nPrice per person\nDZD 1,000–2,000\nFood: 1\nService: 2\nAtmosphere: 2",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/oag5Kchja9LERpgY9",
  }, {
    id: "ahmed amine mekki_An exponential decline in the quality of products ",
    reviewName: "ahmed amine mekki",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "An exponential decline in the quality of products and services and an exponential increase in prices. I have been a  customer at this café since the beginning and today I understood that it is over: a record waiting time, a waiter who comes and goes without understanding what I want and what he has and finally the icing on the cake is a product that is not worthy of what we expect from the place. Once again we see that it is difficult to stay the course for many of our businesses and it is sad",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/mKnYkYqEe2359r6y5",
  }, {
    id: "Nazim Madani_Too expensive and the prices are not fixed at 1000",
    reviewName: "Nazim Madani",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "Too expensive and the prices are not fixed at 1000 da for a coffee, a croissant and an orange juice; in short, it's abused",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/7DEVUvRNXPQye6eLA",
  }, {
    id: "simba sonni_For a coffee with ice cream and a mojito juice 650",
    reviewName: "simba sonni",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "For a coffee with ice cream and a mojito juice 650 Da. Too expensive.",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/GGLAywtsJipRXw4L7",
  }, {
    id: "Wail Bouzaher_No review text found",
    reviewName: "Wail Bouzaher",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/H77uudnbPpj7gMXs9",
  }, {
    id: "Amine Meriem_No review text found",
    reviewName: "Amine Meriem",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/mLqrWANzVtvahFaCA",
  }, {
    id: "Serineee_No review text found",
    reviewName: "Serineee",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/zsybMLRZwUVHYBBm6",
  }, {
    id: "Rym_No review text found",
    reviewName: "Rym",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/VTWJarPdx9tN8wKV6",
  }, {
    id: "Aya_No review text found",
    reviewName: "Aya",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/3XV6VWhWdvdrfQx66",
  }, {
    id: "minion comments_No review text found",
    reviewName: "minion comments",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/wumXnQEYBHjobLMB6",
  }, {
    id: "Asma Mouffok_No review text found",
    reviewName: "Asma Mouffok",
    starRating: "1",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "1 star",
    shareUrl: "https://maps.app.goo.gl/GVEosFoWLHPuzBRr8",
  }, {
    id: "Houda_Well i had a framboise cheesecake and a pressed co",
    reviewName: "Houda",
    starRating: "2",
    responseFromOwner: false,
    reviewText: "Well i had a framboise cheesecake and a pressed coffee, the cheesecake was NOT worth the 400da! It was made poorly and just taste like plain-sugar, the coffee was runny i’ve tasted better.\n\nThe atmosphere wasn’t comfortable, i had to leave because of the noise, not calm at all, but the waiter was super nice.\nMeal type\nOther\nFood: 1\nService: 5\nAtmosphere: 2\nGroup size\n2 people\nSpecial events\nNot sure",
    isHighRating: false,
    starLabel: "2 stars",
    shareUrl: "https://maps.app.goo.gl/hce3qLYc2KAJBEHR6",
  }, {
    id: "Axonek_The place is acceptable out store but it's great i",
    reviewName: "Axonek",
    starRating: "2",
    responseFromOwner: false,
    reviewText: "The place is acceptable out store but it's great in, The taste it's not what i thought for the price and some food are very basics and not really delicious. The coffee is great there\nMeal type\nBreakfast\nPrice per person\nDZD 1–1,000\nFood: 3\nService: 2\nAtmosphere: 2\nRecommended dishes\nCafé L'Or",
    isHighRating: false,
    starLabel: "2 stars",
    shareUrl: "https://maps.app.goo.gl/mbxkYiWmWBPRE1gN8",
  }, {
    id: "Fatima Kastali_The place is well located with fast service and a ",
    reviewName: "Fatima Kastali",
    starRating: "2",
    responseFromOwner: false,
    reviewText: "The place is well located with fast service and a warm welcome. The atmosphere is pleasant and the prices are reasonable. However, I was disappointed by the quality of the products: my coffee was served cold and the brownie was dry.\nService\nDine in\nMeal type\nOther\nFood: 2\nService: 4\nAtmosphere: 4",
    isHighRating: false,
    starLabel: "2 stars",
    shareUrl: "https://maps.app.goo.gl/wcKoPhBMdmAvkPoY7",
  }, {
    id: "Medy_The service too long...very average quality...it's",
    reviewName: "Medy",
    starRating: "2",
    responseFromOwner: false,
    reviewText: "The service too long...very average quality...it's a good location that's all..\nFood: 2\nService: 1\nAtmosphere: 1",
    isHighRating: false,
    starLabel: "2 stars",
    shareUrl: "https://maps.app.goo.gl/whWkBVzhW2auTCdHA",
  }, {
    id: "Mohamed Kaouche_No review text found",
    reviewName: "Mohamed Kaouche",
    starRating: "2",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "2 stars",
    shareUrl: "https://maps.app.goo.gl/qFCtxakk74CkrMFn7",
  }, {
    id: "D. A._I ask for banana juice... a tip for the server: cu",
    reviewName: "D. A.",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "I ask for banana juice... a tip for the server: cut the banana while wearing gloves; it's more hygienic!!!!! You don't add water to the juice!\n\nVery nice coffee, but like in most cafes in Algeria... either they add sugar or they cut it with water...\n\nThe manager seems very friendly and gave us a warm welcome.\n\nThe tea is undrinkable, like in most of the cafes I've tried in Algeria.\n\nAlgeria will be on the menu soon, Amine🙏🙏\nFood: 2\nService: 4\nAtmosphere: 4",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/kgPDBgbZhrsyksoNA",
  }, {
    id: "Jocelyne Morales_I am not a regular at the place in question but it",
    reviewName: "Jocelyne Morales",
    starRating: "3",
    responseFromOwner: true,
    reviewText: "I am not a regular at the place in question but it is worth going there for a coffee ☕ tea ☕ or other cold and hot drinks, not too many people, the exterior and the interior are quite warm. service is good and fast except that the tea we ordered was not hot enough, this is a remark that I make, because the tea must be served hot since it takes several minutes, to say that everywhere we're going nothing is perfect either point of considering the consumption itself is on the table service side, but hey we make do with it.",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/C5C2VywrEudFrrSp6",
  }, {
    id: "AFIF CHAOUCHE Thanina_I would have given it a 5 if it wasn't for the qua",
    reviewName: "AFIF CHAOUCHE Thanina",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "I would have given it a 5 if it wasn't for the quality of service and the hygiene of the toilets!",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/YEfSGLAFVce8CGYE8",
  }, {
    id: "Noura Sauce_No review text found",
    reviewName: "Noura Sauce",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/rbaGVNRGvSC5VJSX8",
  }, {
    id: "Mohammed adnan zeroual_No review text found",
    reviewName: "Mohammed adnan zeroual",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/BsTA52mTuH1i53bg8",
  }, {
    id: "Best Of_No review text found",
    reviewName: "Best Of",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/LbSUqAzaDi8emRi28",
  }, {
    id: "Lydia Azrarak_No review text found",
    reviewName: "Lydia Azrarak",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/fbkfT8W2xYVR61j47",
  }, {
    id: "Silva César_No review text found",
    reviewName: "Silva César",
    starRating: "3",
    responseFromOwner: false,
    reviewText: "No review text found",
    isHighRating: false,
    starLabel: "3 stars",
    shareUrl: "https://maps.app.goo.gl/h3ZVfv1qBHqi7oYh8",
  }, 
]